version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: uploader_ai_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: uploader_ai
      MYSQL_USER: uploader_user
      MYSQL_PASSWORD: uploader_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - uploader_network

  # Redis for Queue
  redis:
    image: redis:7-alpine
    container_name: uploader_ai_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - uploader_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uploader_ai_backend
    restart: unless-stopped
    ports:
      - "5199:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=uploader_user
      - MYSQL_PASSWORD=uploader_pass
      - MYSQL_DATABASE=uploader_ai
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
      - redis
    networks:
      - uploader_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uploader_ai_frontend
    restart: unless-stopped
    ports:
      - "5173:3000"
    environment:
      - VITE_API_URL=http://localhost:5199
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - uploader_network

volumes:
  mysql_data:
  redis_data:

networks:
  uploader_network:
    driver: bridge 